const pokemon = [
  {
    abilities: ["Overgrow"],
    detailPageURL: "/us/pokedex/bulbasaur",
    peso: 15.2,
    weakness: ["Fire", "Psychic", "Flying", "Ice"],
    numero: "001",
    height: 28,
    collectibles_slug: "bulbasaur",
    featured: "true",
    slug: "bulbasaur",
    nombre: "Bulbasaur",
    ThumbnailAltText: "Bulbasaur",
    foto:
      "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/001.png",
    id: 1,
    type: ["grass", "poison"],
  },
  {
    abilities: ["Overgrow"],
    detailPageURL: "/us/pokedex/ivysaur",
    peso: 28.7,
    weakness: ["Fire", "Psychic", "Flying", "Ice"],
    numero: "002",
    height: 39,
    collectibles_slug: "ivysaur",
    featured: "true",
    slug: "ivysaur",
    nombre: "Ivysaur",
    ThumbnailAltText: "Ivysaur",
    foto:
      "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/002.png",
    id: 2,
    type: ["grass", "poison"],
  },
  {
    abilities: ["Overgrow"],
    detailPageURL: "/us/pokedex/venusaur",
    peso: 9999,
    weakness: ["Fire", "Psychic", "Flying", "Ice"],
    numero: "003",
    height: 945,
    collectibles_slug: "venusaur",
    featured: "true",
    slug: "venusaur",
    nombre: "Venusaur",
    ThumbnailAltText: "Venusaur",
    foto:
      "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/003.png",
    id: 3,
    type: ["grass", "poison"],
  },
  {
    abilities: ["Blaze"],
    detailPageURL: "/us/pokedex/charmander",
    peso: 18.7,
    weakness: ["Water", "Ground", "Rock"],
    numero: "004",
    height: 24,
    collectibles_slug: "charmander",
    featured: "true",
    slug: "charmander",
    nombre: "Charmander",
    ThumbnailAltText: "Charmander",
    foto:
      "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/004.png",
    id: 4,
    type: ["fire"],
  },
  {
    abilities: ["Blaze"],
    detailPageURL: "/us/pokedex/charmeleon",
    peso: 41.9,
    weakness: ["Water", "Ground", "Rock"],
    numero: "005",
    height: 43,
    collectibles_slug: "charmeleon",
    featured: "true",
    slug: "charmeleon",
    nombre: "Charmeleon",
    ThumbnailAltText: "Charmeleon",
    foto:
      "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/005.png",
    id: 5,
    type: ["fire"],
  },
  {
    abilities: ["Blaze"],
    detailPageURL: "/us/pokedex/charizard",
    peso: 9999,
    weakness: ["Water", "Electric", "Rock"],
    numero: "006",
    height: 1102,
    collectibles_slug: "charizard",
    featured: "true",
    slug: "charizard",
    nombre: "Charizard",
    ThumbnailAltText: "Charizard",
    foto:
      "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/006.png",
    id: 6,
    type: ["fire", "flying"],
  },
  {
    abilities: ["Torrent"],
    detailPageURL: "/us/pokedex/squirtle",
    peso: 19.8,
    weakness: ["Grass", "Electric"],
    numero: "007",
    height: 20,
    collectibles_slug: "squirtle",
    featured: "true",
    slug: "squirtle",
    nombre: "Squirtle",
    ThumbnailAltText: "Squirtle",
    foto:
      "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/007.png",
    id: 7,
    type: ["water"],
  },
  {
    abilities: ["Torrent"],
    detailPageURL: "/us/pokedex/wartortle",
    peso: 49.6,
    weakness: ["Grass", "Electric"],
    numero: "008",
    height: 39,
    collectibles_slug: "wartortle",
    featured: "true",
    slug: "wartortle",
    nombre: "Wartortle",
    ThumbnailAltText: "Wartortle",
    foto:
      "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/008.png",
    id: 8,
    type: ["water"],
  },
  {
    abilities: ["Torrent"],
    detailPageURL: "/us/pokedex/blastoise",
    peso: 9999,
    weakness: ["Grass", "Electric"],
    numero: "009",
    height: 984,
    collectibles_slug: "blastoise",
    featured: "true",
    slug: "blastoise",
    nombre: "Blastoise",
    ThumbnailAltText: "Blastoise",
    foto:
      "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/009.png",
    id: 9,
    type: ["water"],
  },
  {
    abilities: ["Shield Dust"],
    detailPageURL: "/us/pokedex/caterpie",
    peso: 6.4,
    weakness: ["Fire", "Flying", "Rock"],
    numero: "010",
    height: 12,
    collectibles_slug: "caterpie",
    featured: "true",
    slug: "caterpie",
    nombre: "Caterpie",
    ThumbnailAltText: "Caterpie",
    foto:
      "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/010.png",
    id: 10,
    type: ["bug"],
  },
  {
    abilities: ["Shed Skin"],
    detailPageURL: "/us/pokedex/metapod",
    peso: 21.8,
    weakness: ["Fire", "Flying", "Rock"],
    numero: "011",
    height: 28,
    collectibles_slug: "metapod",
    featured: "true",
    slug: "metapod",
    nombre: "Metapod",
    ThumbnailAltText: "Metapod",
    foto:
      "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/011.png",
    id: 11,
    type: ["bug"],
  },
  {
    abilities: ["Compound Eyes"],
    detailPageURL: "/us/pokedex/butterfree",
    peso: 9999,
    weakness: ["Fire", "Flying", "Electric", "Ice", "Rock"],
    numero: "012",
    height: 669,
    collectibles_slug: "butterfree",
    featured: "true",
    slug: "butterfree",
    nombre: "Butterfree",
    ThumbnailAltText: "Butterfree",
    foto:
      "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/012.png",
    id: 12,
    type: ["bug", "flying"],
  },
  {
    abilities: ["Shield Dust"],
    detailPageURL: "/us/pokedex/weedle",
    peso: 7.1,
    weakness: ["Fire", "Psychic", "Flying", "Rock"],
    numero: "013",
    height: 12,
    collectibles_slug: "weedle",
    featured: "true",
    slug: "weedle",
    nombre: "Weedle",
    ThumbnailAltText: "Weedle",
    foto:
      "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/013.png",
    id: 13,
    type: ["bug", "poison"],
  },
  {
    abilities: ["Shed Skin"],
    detailPageURL: "/us/pokedex/kakuna",
    peso: 22,
    weakness: ["Fire", "Psychic", "Flying", "Rock"],
    numero: "014",
    height: 24,
    collectibles_slug: "kakuna",
    featured: "true",
    slug: "kakuna",
    nombre: "Kakuna",
    ThumbnailAltText: "Kakuna",
    foto:
      "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/014.png",
    id: 14,
    type: ["bug", "poison"],
  },
  {
    abilities: ["Adaptability"],
    detailPageURL: "/us/pokedex/beedrill",
    peso: 89.3,
    weakness: ["Fire", "Psychic", "Flying", "Rock"],
    numero: "015",
    height: 55,
    collectibles_slug: "beedrill",
    featured: "true",
    slug: "beedrill",
    nombre: "Beedrill",
    ThumbnailAltText: "Beedrill",
    foto:
      "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/015.png",
    id: 15,
    type: ["bug", "poison"],
  },
  {
    abilities: ["Keen Eye", "Tangled Feet"],
    detailPageURL: "/us/pokedex/pidgey",
    peso: 4,
    weakness: ["Electric", "Ice", "Rock"],
    numero: "016",
    height: 12,
    collectibles_slug: "pidgey",
    featured: "true",
    slug: "pidgey",
    nombre: "Pidgey",
    ThumbnailAltText: "Pidgey",
    foto:
      "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/016.png",
    id: 16,
    type: ["normal", "flying"],
  },
  {
    abilities: ["Keen Eye", "Tangled Feet"],
    detailPageURL: "/us/pokedex/pidgeotto",
    peso: 66.1,
    weakness: ["Electric", "Ice", "Rock"],
    numero: "017",
    height: 43,
    collectibles_slug: "pidgeotto",
    featured: "true",
    slug: "pidgeotto",
    nombre: "Pidgeotto",
    ThumbnailAltText: "Pidgeotto",
    foto:
      "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/017.png",
    id: 17,
    type: ["normal", "flying"],
  },
  {
    abilities: ["No Guard"],
    detailPageURL: "/us/pokedex/pidgeot",
    peso: 111.3,
    weakness: ["Electric", "Ice", "Rock"],
    numero: "018",
    height: 87,
    collectibles_slug: "pidgeot",
    featured: "true",
    slug: "pidgeot",
    nombre: "Pidgeot",
    ThumbnailAltText: "Pidgeot",
    foto:
      "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/018.png",
    id: 18,
    type: ["normal", "flying"],
  },
  {
    abilities: ["Gluttony", "Hustle"],
    detailPageURL: "/us/pokedex/rattata",
    peso: 8.4,
    weakness: ["Fairy", "Bug", "Fighting"],
    numero: "019",
    height: 12,
    collectibles_slug: "rattata",
    featured: "true",
    slug: "rattata",
    nombre: "Rattata",
    ThumbnailAltText: "Rattata",
    foto:
      "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/019.png",
    id: 19,
    type: ["dark", "normal"],
  },
  {
    abilities: ["Gluttony", "Hustle"],
    detailPageURL: "/us/pokedex/raticate",
    peso: 56.2,
    weakness: ["Fairy", "Bug", "Fighting"],
    numero: "020",
    height: 28,
    collectibles_slug: "raticate",
    featured: "true",
    slug: "raticate",
    nombre: "Raticate",
    ThumbnailAltText: "Raticate",
    foto:
      "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/020.png",
    id: 20,
    type: ["dark", "normal"],
  },
  ];
